server:
  port: 80

spring:
    datasource:
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      url: ENC(t/K1L+amITrxQDmgGW6gDg5YqzOaRLGQU8VcjqpH+P4gJ5Fn0Z3cApmJu9mmUB/ggINCXS2G/kM=)
      username: ENC(/cfBuPPvDoDCYGEPmnZZyg==)
      password: ENC(R1L/gnSgUGntop24Zg15PO1KZnXoDIvZ)

mybatis:
  mapper-locations: classpath:mapper/**/*.xml

logging:
  charset:
    console: UTF-8
  level:
    root: info
    jdbc: off
    jdbc.sqlonly: off
    jdbc.sqltiming: debug
    jdbc.audit: off
    jdbc.resultset: off
    jdbc.resultsettable: off
    jdbc.connection: off

jasypt:
  encryptor:
    bean: jasyptStringEncryptor

