server:
  port: 8080

spring:
    datasource:
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      url: ENC(E37qn5OGT7+x3ZcM9lGNOH1+Tc4iCbtZRGcKBSknDoz2JtT5I5wfRbQ1rIlfL3roFyrQhGJYMB8=)
      username: ENC(/cfBuPPvDoDCYGEPmnZZyg==)
      password: ENC(R1L/gnSgUGntop24Zg15PO1KZnXoDIvZ)

mybatis:
  mapper-locations: classpath:mapper/**/*.xml

logging:
  charset:
    console: UTF-8
  level:
    root: info
    jdbc: off
    jdbc.sqlonly: off
    jdbc.sqltiming: debug
    jdbc.audit: off
    jdbc.resultset: off
    jdbc.resultsettable: off
    jdbc.connection: off

jasypt:
  encryptor:
    bean: jasyptStringEncryptor

